title = "Vadym Popov"
publishDir = "docs"
paginate = 5

author = "Vadym Popov"
copyright = "Copyright (c) 2008 - 2014, Vadym Popov; all rights reserved."
canonifyurls = true
theme = "hugo-code-editor-theme"

[params]
    author = "John Doe"
    locale = "en-US"

disqusShortname = "vadympopov"
googleAnalytics = "UA-103006315-1"
paginate = 7
canonifyurls = true


